version: "3"

services:
  web:
    container_name: web
    build:
      context: ./docker/web/debian
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html:rw
      - ./cgi-bin:/var/www/cgi-bin:rw
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:8.0
    env_file:
      - ./docker/db/db.env
    expose:
      - 3306
    volumes:
      - ./docker/db/data:/var/lib/mysql

  mail:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 8025:8025
    expose:
      - 1025
    env_file:
      - ./docker/mail/mail.env
    volumes:
      - ./docker/mail/tmp:/tmp:rw
