version: "3"

services:
  web:
    container_name: ${WEB_CONTAINER_NAME}
    build:
      context: ./docker/web/${WEB_CONTAINER_OS}
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html:rw
      - ./cgi-bin:/var/www/cgi-bin:rw
  db:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./docker/db/data:/var/lib/mysql
    command: mysqld --character-set-server=UTF8MB4 --collation-server=utf8mb4_unicode_ci
  mail:
    container_name: ${MAIL_CONTAINER_NAME}
    image: mailhog/mailhog
    ports:
      - ${MAIL_HTTP_PORT}:${MAIL_HTTP_PORT}
    expose:
      - ${MAIL_SMTP_PORT}
    environment:
      MH_STORAGE: ${MH_STORAGE}
      MH_MAILDIR_PATH: ${MH_MAILDIR_PATH}
    volumes:
      - ./docker/mailhog/:${MH_MAILDIR_PATH}:rw
